### ISSUE TITLE
DSL grammar

### ISSUE THREAD

**Issue by marquesarthur** [MattRidderikhoff/DashboardGenerator#1]
Hi everyone,

Would be so kind and add an example of the DSL in either your README file or as another markdown file. I want to double check your DSL idea and ensure that you are on the right path.

Thanks in advance,
Arthur

**Comment by richard-chiang** [comment]
https://github.com/MattRidderikhoff/DashboardGenerator/pull/4 
Please help me review and point out any mistakes or misses that I may have made.

**Comment by marquesarthur** [comment]
Nice work thus far! I'm not entirely sure how you link your dataset to your grammar though. 
Is it an argument of the DSL? Like dsl dataset
Or is there a load dataset statement that I missed?

**Comment by MattRidderikhoff** [comment]
@marquesarthur this is actually a feature we are working on. We will allow users to upload an arbitrary amount of datasets, and then they can set them as variables (load them) in the DSL, and then each graph will have an associated dataset

**Comment by marquesarthur** [comment]
cool. then, I'll close the issue
